// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyochcamcuhzwqvrjsvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5b2NoY2FtY3VoendxdnJqc3ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTEyMDYsImV4cCI6MjA3Mzg2NzIwNn0.kAEDY_7IYPpPWseDf0m1OVuM3Dbw5GQiFdQcTHYTEuQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});